server:
  servlet:
    context-path: /cms

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CMS?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://66.42.93.215:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wonderful



#mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
type_alias_package: com.superfly.cms.entity
#打印sql
logging:
  level:
      com.superfly.cms.dao : debug

